name: Build signed release apk

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"
jobs:
  pre_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.14+101'
          distribution: 'temurin'
          cache: gradle
      - name: Checkout Android Keystore
        uses: actions/checkout@v2
        with:
          repository: ayasa520/keystore
          token: ${{ secrets.KEYSTORE_TOKEN }}
          path: keystore
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  unit_tests:
    needs: [pre_build]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test

  android_tests:
    needs: [pre_build]
    runs-on: [macos-latest]
    steps:
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.14+101'
          distribution: 'temurin'
      - uses: actions/checkout@v2
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  build_apk:
    needs: [unit_tests, android_tests, pre_build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Checkout Android Keystore
        uses: actions/checkout@v2
        with:
          repository: ayasa520/keystore
          token: ${{ secrets.KEYSTORE_TOKEN }}
          path: keystore

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build signed release apk
        run: ./gradlew assembleRelease

      - name: Upload signed release apk
        uses: actions/upload-artifact@v2
        with:
          name: apk-release
          path: app/build/outputs/apk/release

      - name: Compress files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -j smartdock.zip app/build/outputs/apk/release/app-release.apk app/src/main/assets/permissions_cu.axel.smartdock.xml
      - name: "Upload Release Assets"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            app/build/outputs/apk/release/app-release.apk
            smartdock.zip
